// 凱文大叔 — AI 賦能全端開發 · Hahow 課程銷售頁資料
// 內容整理自課程內容.md（kevintsai1202/ai-full-stack）
window.COURSE = {
  titleZh: "AI 賦能全端開發：從零打造企業級智慧應用",
  titleEn: "AI-Empowered Full-Stack: Building Enterprise-Grade Smart Apps",
  tagline: "用一套 AI CRM 實戰專案，把 Spring Boot、Spring AI 與 React 串成可上線的企業級智慧應用。",
  instructor: "凱文大叔 Uncle Kevin",
  pricing: {
    early: 3680,
    list: 5200,
    goalPct: 72,
    goalLabel: "募資目標達成率",
    backers: 1284,
    daysLeft: 18,
  },
  outcomes: [
    { t: "從零搭起全端骨架", d: "建立 Spring Boot + React 的 AI CRM 專案，前後端分離、可啟動可驗證。" },
    { t: "企業級後端分層", d: "用 Spring MVC 設計客戶、商機、互動紀錄與任務管理 API，分層清楚。" },
    { t: "可維護的資料模型", d: "用 Spring Data JPA、Specification 與 Flyway 建立可遷移的資料庫。" },
    { t: "登入與權限控管", d: "用 Spring Security + JWT 完成登入、角色與 API 授權保護。" },
    { t: "可串流的 AI 助理", d: "用 Spring AI ChatClient + SSE 打造 token-by-token 回應的 CRM 助理。" },
    { t: "讓 AI 讀真實資料", d: "用 tool calling 與 pgvector RAG，讓 AI 引用文件、不憑空亂答。" },
  ],
  features: [
    { icon: "layers", t: "一條產品開發路線", d: "不是把多門課拼在一起，而是用同一套 AI CRM 範例，把每個技術放進同一條開發路線。" },
    { icon: "shield-check", t: "技術由工具算、文字由模型寫", d: "所有金額、訂單、權限由 Java domain service 提供；LLM 只負責摘要、分類、建議與草稿。" },
    { icon: "bot", t: "AI Agent 協作開發", d: "每單元都附 AI 提示詞主題：先讀需求、再產程式、最後驗證，產出可測試可維運的程式碼。" },
    { icon: "git-branch", t: "章章相連、產出累積", d: "每一章的產出都成為下一章的基礎，避免只學到零散範例。" },
  ],
  audience: [
    "已具備 Java 基礎，想把 Spring Boot、React 與 AI 串成完整產品的工程師。",
    "會寫基本 REST API，但還不熟企業級分層、權限、錯誤處理與前後端整合的開發者。",
    "想理解 Spring AI 與 RAG 如何落地在真實 JVM 系統，而不只做聊天機器人 demo 的後端工程師。",
    "想用 AI Agent 協作開發，但希望產出可測試、可維運、可上線程式碼的全端工程師。",
  ],
  stack: ["Java 21", "Spring Boot 4", "Spring MVC", "Spring Data JPA", "PostgreSQL + pgvector", "Flyway", "Spring Security + JWT", "SpringDoc OpenAPI", "Spring AI 2.0", "React + TypeScript", "Vite"],
  units: [
    { n: "01", t: "開發環境、專案骨架與 AI 協作流程", out: "可啟動的 full-stack monorepo", tags: ["環境建置", "Monorepo", "AI 協作"],
      points: ["JDK 21 / Maven / Node / Docker 安裝與驗證", "Spring Initializr + Vite 建立前後端", "後端 /api/health、前端健康狀態紅綠燈", "第一份 AI Agent 提示詞：檢查本機環境"] },
    { n: "02", t: "Spring MVC、REST API 與 CRM Domain Modeling", out: "客戶與互動紀錄 API", tags: ["Spring MVC", "REST", "DTO"],
      points: ["DispatcherServlet 與請求生命週期", "Customer / Contact / Interaction / Opportunity 拆解", "Controller / Service 分工與 DTO 邊界", "Bean Validation 與可讀的 400 錯誤"] },
    { n: "03", t: "PostgreSQL、Flyway、JPA 與動態查詢", out: "CRM 資料庫與查詢服務", tags: ["JPA", "Flyway", "Specification"],
      points: ["Docker Compose 啟動 PostgreSQL + pgvector", "Flyway 命名規則與 migration 策略", "Entity mapping、關聯與 audit 欄位", "用 Specification 組合多條件搜尋"] },
    { n: "04", t: "Spring Security、JWT、OpenAPI 與企業級錯誤處理", out: "安全可測的後端 API", tags: ["Security", "JWT", "OpenAPI"],
      points: ["Filter chain 與密碼雜湊", "JWT 簽發、角色與過期時間", "保護 /api/customers/**、/api/opportunities/**", "@ControllerAdvice + ProblemDetail 統一錯誤"] },
    { n: "05", t: "React CRM 工作台與前後端整合", out: "可登入的 CRM UI", tags: ["React", "TypeScript", "整合"],
      points: ["API client、JWT 儲存與自動帶 token", "CRM Dashboard 資訊架構", "客戶列表、搜尋、客戶詳情頁", "商機看板與 loading / error / empty 狀態"] },
    { n: "06", t: "Spring AI ChatClient、SSE 與 tool calling", out: "AI CRM 助理聊天室", tags: ["Spring AI", "SSE", "Tool Calling"],
      points: ["ChatClient 與 system prompt 設計", "SSE endpoint 與 React 串流顯示", "CrmInsightTools：客戶統計、商機健康分數", "信任邊界：數字由工具算、文字由模型寫"] },
    { n: "07", t: "RAG、pgvector、MCP 與知識庫擴充", out: "可引用文件的 AI 建議", tags: ["RAG", "pgvector", "MCP"],
      points: ["文件切片、embedding 與 metadata 設計", "pgvector schema 與檢索流程", "AI 推薦產品時引用知識庫來源", "domain tool / RAG / MCP 的選用判斷"] },
    { n: "08", t: "結訓專案衝刺與 Demo Day 驗收", out: "可展示的完整 AI CRM", tags: ["整合", "測試", "Demo Day"],
      points: ["端到端整合：CORS、JWT、seed data 對齊", "三種典型客戶場景的端到端測試", "上線檢查清單：安全 / 效能 / 可觀測性", "Demo Day 腳本：登入→客戶→AI→RAG→Swagger"] },
  ],
  faq: [
    { q: "這門課適合完全沒寫過 Java 的新手嗎？", a: "建議先具備基本 Java 語法與 REST API 概念。課程著重在企業級分層、整合與 AI 落地，而不是從零教語法；若你寫過簡單的 API，就能順利跟上。" },
    { q: "課程用的是哪些技術版本？", a: "Java 21、Spring Boot 4.0.x、Spring AI 2.0.x (GA)、PostgreSQL + pgvector、React + TypeScript + Vite。開發環境以 Windows + PowerShell 7+ 示範，macOS / Linux 也可比照操作。" },
    { q: "這跟坊間「呼叫 LLM API」的課有什麼不同？", a: "我們不只教你呼叫 LLM，而是帶你把 AI 放進一套真正能上線的企業系統：資料庫、權限、前端、RAG、工具呼叫與端到端整合一次到位。" },
    { q: "Embabel / AI Agent 框架會教嗎？", a: "Embabel 的 GOAP、Action、Goal、Blackboard 內容會以選修附錄提供。Spring AI 2.0 GA 已發行，Embabel 已可搭配 Spring Boot 4 使用。" },
    { q: "買了之後可以看多久？", a: "購買後可不限次數、無限期觀看，課程更新也會免費同步給你。" },
    { q: "完成課程後我會做出什麼？", a: "一套可登入、可查客戶、可引用知識庫、可產生業務建議、可追蹤 AI 執行過程的企業級 AI CRM，並能在 Demo Day 完整跑通展示。" },
  ],
};
